vscode:
  extensions:
    - Swellaby.vscode-rust-test-adapter@0.11.0:Xg+YeZZQiVpVUsIkH+uiiw==
    - serayuzgur.crates@0.4.7:HMkoguLcXp9M3ud7ac3eIw==
    - belfz.search-crates-io@1.2.1:kSLnyrOhXtYPjQpKnMr4eQ==
